# Generated by Django 5.1.1 on 2024-09-29 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_theme_remove_country_name_remove_state_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='theme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='databases.theme', verbose_name='Tema'),
            preserve_default=False,
        ),
    ]
