# Generated by Django 5.1.1 on 2024-09-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0007_rename_moves_move'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'verbose_name': 'Jogada', 'verbose_name_plural': 'Jogadas'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Palavra', 'verbose_name_plural': 'Palavras'},
        ),
    ]
