# Generated by Django 5.1.1 on 2024-10-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0008_alter_country_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='answer_status',
            field=models.BooleanField(default=False, verbose_name='Certo/Errado'),
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='databases.game', verbose_name='Jogo'),
            preserve_default=False,
        ),
    ]
