# Generated by Django 5.1.1 on 2024-10-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0009_move_answer_status_move_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
