# Generated by Django 5.1.1 on 2024-10-07 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0011_remove_move_answer_status_move_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='owner',
        ),
    ]
